openapi: 3.1.0
info:
  title: auth-service
  version: 1.0.0
  description: |
    auth-service is an identity provider to authenticate and authorize client api
  contact:
    name: Raj, Pushp
    email: pushp277@gmail.com
servers:
  # Added by API Auto Mocking Plugin
  - description: |
      local-system
    url: http://localhost:8003/

paths:
  /api/v1/create:
    post:
      tags:
        - client api
      operationId: createNewUser
      summary: create new user

      requestBody:
        required: true
        description: |
          info regarding create User endpoint
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        '200':
          description: user created successfully


        '400':
          description: user already exists or any field is missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateNewUserError'


  /api/v1/oauth2/authorize:
    get:
      tags:
        - client api
      summary: authorize user
      operationId: authorizeUser
      parameters:
        - name: client_id
          in: query
          required: true
          schema:
            type: string

        - name: redirect_uri
          in: query
          required: true
          schema:
            type: string

        - name: SESSION_
          in: cookie
          required: false
          schema:
            type: string

        - name: scope
          in: query
          schema:
            type: string

      responses:
        '302':
          description: redirect to base url with code
          headers:
            Location:
              schema:
                type: string
                examples:
                  - "http://localhost:3000/login?accessCode=134"
            Set-Cookie:
              description: Successful
              schema:
                type: string
                examples:
                  - JSESSIONID=abcde12345; Path=/; HttpOnly; Secure
        '400':
          description: authoriztion failed for this client
          headers:
            Location:
              schema:
                type: string
                examples:
                  - "http://localhost:3000/callback?accessCode=null"

  /api/v1/oauth2/token:
    post:
      tags:
        - client api
      summary: exchange access_code
      operationId: exchangeToken
      description: exhange access_code for accessToken and refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTokenRequest"

      responses:
        '200':
          description: exchange token response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTokenResponse"

        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTokenBadRequest"

  /api/v1/oauth2/refresh:
    post:
      summary: generate accessToken and refreshToken
      operationId: generateRefreshToken
      tags:
        - client api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'

      responses:
        "200":

          description: response to get value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshTokenResponse'

  /api/v1/login:
    post:
      tags:
        - client api
      summary: allow user to login to the system
      operationId: loginUser
      description: client login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginRequest'

      responses:
        '200':
          description: login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'


        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginValidationError'


  /api/v1/logout:
    delete:
      summary: revoke user refresh token and session
      tags:
        - client api
      operationId: logoutUser
      description: client logout
      parameters:
        - name: SESSION_
          in: cookie
          required: true
          schema:
            type: string
            examples:
              - JSESSIONID_123

      responses:
        '204':
          description: Logout user by expiring session and refreshToken


  /api/oauth2/github/callback:
    get:
      summary: callback with code and state
      tags:
        - "outh2 callback"
      operationId: githubCallback
      description: callback send by github id provider
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
            example: ABC123
        - name: state
          in: query
          required: true
          schema:
            type: string
            example: xyz

      responses:
        '302':
          description: found response send by github oauth2

        '400':
          description: Validation Error

  /api/oauth2/google/callback:
    get:
      summary: callback with code and state
      tags:
        - "outh2 callback"
      operationId: googleCallback
      description: callback send by google id provider
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
            example: ABC123
        - name: state
          in: query
          required: true
          schema:
            type: string
            example: xyz

      responses:
        '302':
          description: found response send by google oauth2

        '400':
          description: Vaidation Error


components:
  schemas:
    User:
      type: object
      required:
        - username
        - firstName
        - lastName
        - password
      properties:
        username:
          type: string
          examples:
            - pushp.raj
          minLength: 3
          maxLength: 50
        firstName:
          type: string
          minLength: 1
          maxLength: 50
          examples:
            - Pushp
        lastName:
          type: string
          examples:
            - Raj
          minLength: 1
          maxLength: 50
        dateOfBirth:
          type: string
          format: date
          examples:
            - 1999-11-08
        password:
          type: string
          format: password
          minLength: 3
          examples:
            - "Strong!P@ssword"
        contactDetails:
          allOf:
            - $ref: '#/components/schemas/ContactDetails'
    ContactDetails:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          examples:
            - pushp.raj@email.com
        phoneNumber:
          type: string
          examples:
            - 08043325354
          pattern: "^\\d{10,11}$"
        address:
          allOf:
            - $ref: '#/components/schemas/Address'

    Address:
      type: object
      properties:
        line1:
          type: string
          examples:
            - 1-29
        line2:
          type: string
          examples:
            - 2-401
        city:
          type: string
          examples:
            - Yokohama
        prefecture:
          type: string
          examples:
            - Kanagawa
        postalCode:
          type: integer
          format: int32
          examples:
            - 2260019

    CreateNewUserError:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          examples:
            - BAD_REQUEST


    CreateTokenRequest:
      type: object
      required:
        - authorization-code
        - client-id
        - client-secret
      properties:
        authorization-code:
          type: string
          examples:
            - abc123
        client-id:
          type: string
          examples:
            - client-id
        client-secret:
          type: string
          examples:
            - client-srecet
    CreateTokenResponse:
      type: object
      properties:
        accessToken:
          type: string
          examples:
            - abc1234
        refreshToken:
          type: string
          examples:
            - abc2345

    CreateTokenBadRequest:
      type: object
      properties:
        code:
          type: string
          examples:
            - BAD_REQUEST

    RefreshTokenRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string
          examples:
            - abc123

    RefreshTokenResponse:
      type: object
      required:
        - refreshToken
        - accessToken
      properties:
        refreshToken:
          type: string
        accessToken:
          type: string

    LogoutRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string

    LoginRequest:
      type: string
      examples:
        - pushp.raj&Strong!P@ssword


    LoginResponse:
      type: object
      properties:
        accessCode:
          type: string
          examples:
            - abcd123==

    LoginValidationError:
      type: object
      properties:
        message:
          type: string
          examples:
            - user doesn't exist

    JWTClaims:
      type: object
      properties:
        jti:
          type: string
          examples:
            - abc123
        aud: # client Id
          type: string
          examples:
            - "11001"
        exp:
          type: number
          format: int64
          examples:
            - 23434235
        iat:
          type: number
          format: int64
          examples:
            - 23434235
        role:
          type: string
          examples:
            - "USER"
        sub: # username
          type: string
          examples:
            - pushp.raj
        iss:
          type: string
          examples:
            - SageDelta


